### ISSUE TITLE
Comparability of gene set of different sizes

### ISSUE THREAD

**Issue by kvittingseerup** [carmonalab/UCell#1]
Hi 

I'm very interested in UCell - it looks very promising.

Are the scores derived from different gene sets of different sizes comparable? (e.g. can I interpret which of two gene sets are more active / expressed?).

Btw to convince more people you could also compare to ssGSEA.

Cheers
Kristoffer

**Comment by mass-a** [comment]
Thanks for your comments!

UCell scores are normalized by the size of the gene set (see the formula for the scores in the preprint), so they should be comparable regardless of gene set size. You can test this by evaluating the UCell scores for a large gene set and compare it to random subsets of the gene set of different sizes.

We made UCell to score and annotate individual cells, but it is true that global statistics could also be calculated to perform similar analyses to single sample GSEA.

Cheers and thanks.

**Comment by kvittingseerup** [comment]
Thanks for the quick response :-)
