### ISSUE TITLE
Reporting significance level with the U-Statistic?

### ISSUE THREAD

**Issue by cnk113** [carmonalab/UCell#12]
Hello,

I was wondering if you can also return the p-value from the Mann-Whitney U test?

Best,
Chang

**Comment by mass-a** [comment]
Hello Chang,
I don't think it's a good idea to calculate a p-value for each cell. Instead, I would suggest to compare UCell scores for a given signatures between *groups of cells* (e.g. unsupervised clusters). If you draw distributions of UCell scores per cluster, you would be able to evaluate if they differ significantly using e.g. a t-test or a KS test. 

Best,
-m

**Comment by cnk113** [comment]
Thanks, your suggestions worked for my case!
