### ISSUE TITLE
For Seurat, must the data be scaled and/or normalized before using AddModuleScore_UCell?

### ISSUE THREAD

**Issue by ksaunders73** [carmonalab/UCell#13]
Hello!

In Seurat, you can both scale and normalize the data with [ScaleData()](https://github.com/satijalab/seurat/blob/master/man/ScaleData.Rd) and [NormalizeData()](https://github.com/satijalab/seurat/blob/master/man/NormalizeData.Rd) respectively. 

From [issue 3892 on Seurat's github](https://github.com/satijalab/seurat/issues/3892), it is implied that `ScaleData()` is mainly just for PCA. This makes me wonder, should the Seurat object be normalized, or scaled, or both, before running `AddModuleScoreUCell()`?

Thank you for reading!

**Comment by mass-a** [comment]
Hello Kaytlin,

short answer: no, you do not need to normalize or rescale the data to apply UCell. UCell scores are calculated for each cell, and are based only on the relative ranking of the genes in the signature. If you apply a normalization that preserves the ranking of the genes (e.g. a log-normalization), you can verify that you obtain exactly the same UCell scores before or after normalization.

As for scaling across genes, I agree that it should not be used outside of PCA pre-processing.

Best,
-m

**Comment by ksaunders73** [comment]
Thank you very much @mass-a! This is very helpful!
