### ISSUE TITLE
issues downloading cell

### ISSUE THREAD

**Issue by carlosaya2** [carmonalab/UCell#17]
hi there, 

I trying to install UCell but it seems that there is some issues installing it. I tried Bioconductor and github options with no success.   
 
<img width="825" alt="image" src="https://user-images.githubusercontent.com/61134130/160593325-695d8465-bde3-42e7-ab05-9710ae194d52.png">

<img width="696" alt="image" src="https://user-images.githubusercontent.com/61134130/160593408-eccc283a-5af0-4ccc-8711-4b5d59953621.png">

I will highly appreciate any help and guidance that you can provide.
Cheers,
 
Carlos

**Comment by mass-a** [comment]
Hello Carlos,

as the errors seems to suggest, you are probably trying to install to a location you cannot access. I can also see "Installation paths not writable" – can you check you have write permission and free space on your download location?

Best
-massimo
