### ISSUE TITLE
struggling to instal package

### ISSUE THREAD

**Issue by ncedi12** [carmonalab/UCell#19]
Hi there, I am really interested in using your package but I just cannot install it. It seems as though the dependencies do not get installed, which prevents the package being rejected. the problem arises with UCell installation.
As below

> remotes::install_github("carmonalab/UCell", ref="v1.3")
Downloading GitHub repo carmonalab/UCell@v1.3
✓  checking for file ‘/private/var/folders/z_/4dkjn12140n0hywjwxf06gdc0000gn/T/RtmpqC3oae/remotesee0b658e96d2/carmonalab-UCell-f815356/DESCRIPTION’ ...
─  preparing ‘UCell’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘UCell_1.3.1.tar.gz’
   
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
Calls: source -> file
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'renv/activate.R': No such file or directory
Execution halted
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/z_/4dkjn12140n0hywjwxf06gdc0000gn/T//RtmpqC3oae/fileee0b744fe914/UCell_1.3.1.tar.gz’ had non-zero exit status

Please advise as to how I can overcome this issue.

**Comment by mass-a** [comment]
Hello,
can you tell us what is your OS, R version and the result of running `sessionInfo()`?
