### ISSUE TITLE
Installing UCell on R-4.1 and Bioconductor < 3.15

### ISSUE THREAD

**Issue by vkartha** [carmonalab/UCell#23]
Hi there - I was interested in installing this since it is a dependency for scGate. However, I'm running R v 4.1.2, and this won't install for R < 4.2

Error:
package 'UCell' requires R >= 4.2.0

Is there a reason there is a subversion constraint that prohibits someone with R >4.0. from running this? I also wasn't able to download it from Bioconductor because of the BioCManager version (similar, it's not that old, but requires a later version:

package ‘UCell’ is not available for Bioconductor version '3.14'   )

Thanks

**Comment by mass-a** [comment]
Hello Vinay

you can install previous versions of UCell from Github by specifying the version tag, e.g.:
```r
remotes::install_github("carmonalab/UCell", ref="v2.0")
```
In your case version 2.0 should be compatible with R-4.1.

Best
-m
