### ISSUE TITLE
Could the UCell module score be used as a metric for co-expression within your gene set?

### ISSUE THREAD

**Issue by Ruth-hals** [carmonalab/UCell#26]
Hi, thank you for developing this tool, very useful!

I'm interested in comparing coexpression levels between different gene sets.
Could I use the module score as a metric for co-expression within a gene set? and then compare these amongst different gene sets?
I could then use this as a read-out that genes in gene set A are more co-expressed than in gene set B based on pairwise test for all module scores?

Thanks for the info,
Cheers,
Ruth

**Comment by mass-a** [comment]
Hello Ruth,

I am not sure one can interpret UCell scores as a measure of co-expression. For example, you may have a simple signature made of genes A and B, and two cases; 1) gene A is highly expressed and gene B has zero expression; 2) gene A and B have both medium expression. You will in generally obtain similar UCell scores for case 1) and 2), therefore they are not a direct evidence of co-expression.

You may want to look into methods specifically developed for single-cell co-expression analysis, such as [WGCNA](https://smorabit.github.io/hdWGCNA/articles/basic_tutorial.html) or others.

Best
-m
