### ISSUE TITLE
How to interpret negative and zero UCell scores

### ISSUE THREAD

**Issue by ksaunders73** [carmonalab/UCell#4]
Hello!

I'm very new to statistics, so it may already be answered, but I just wanted to ask a clarifying question on how to interpret negative and zero UCell scores (do they represent genes being expressed less and equal to the mean respectively? Zero expression or negative expression?). I ran the equivalent of the following (though I did Z score transform it as well): 

```
gene.sets <- list(c("CD2","CD3E","CD3D")
SeuratObject <- AddModuleScore_UCell(SeuratObject,features = gene.sets, name = "gene")
SeuratObject $signature_1gene <- (SeuratObject $signature_1gene - mean(SeuratObject $signature_1gene )) / sd(SeuratObject $signature_1gene )
```

Thanks for reading!

**Comment by mass-a** [comment]
Hello and thanks for using the tool.

By definition (check out the formula in the [paper](https://www.sciencedirect.com/science/article/pii/S2001037021002816)) UCell scores are bound between 0 and 1, so you won't have negative scores.

UCell scores are based on relative ranks, so they measure how the genes in your signature rank when compared to all other genes. The extreme cases would be that the three genes in your signature are the top three expressed genes (UCell score=1) or that all three have zero expression, in which case UCell score=0. 

I hope this helps.

PS: you can more easily name signatures by assigning names to your list e.g.:
```
gene.sets <- list(mysignature1=c("CD2","CD3E","CD3D"),
                  mysignature2=c("CD19","BANK1","MS4A1"))
```

**Comment by ksaunders73** [comment]
Hello @mass-a ! 

Thank you very much for replying and thank you as well for the great tool! I don't know if I am doing something wrong in terms of providing the genes or setting the assay wrong (I keep it at the RNA assay), or if the Z score transformation is affecting it somehow, but I do get negative scores in some of my UCell signatures following the structure of the code I provided in my question:

![image](https://user-images.githubusercontent.com/62159599/129074760-a850667b-7977-41bd-8493-116de9bd22b3.png)

**Comment by mass-a** [comment]
Ah ok, I think I understand your question now.

If you transform to Z-scores you will get positive and negative values for any distribution of values (unless they are all equal).

In your example, negative Z-scores simply correspond to cells with UCell scores below the mean, for the given signature. And the Z-score value will tell you by how many standard deviation they deviate from the mean. But keep in mind you are comparing cells, not genes as you hinted in the original question.

**Comment by ksaunders73** [comment]
Hello @mass-a ! That makes sense, thank you very much!
